ConsumeWebServices/Controllers/PaymentController.cs
using ConsumeWebServices.Models;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web.Http;
using System.Web.Mvc;

namespace ConsumeWebServices.Controllers
{
    public class PaymentController : Controller
    {
        // GET: Payment
        public ActionResult voir()
        {
            return View();
        }


        [System.Web.Http.HttpGet]
        public ActionResult var()
        {
            return View("Create");
        }



        [System.Web.Http.HttpPost]
        public ActionResult Create(CardDetails c)
        { 
            var clientid = Session["clientid"];
            c.number = "4242424242424242";
            c.expMonth = 3;
            c.expYear = 2025;
            c.cvc = "123";
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:8085");
            client.PostAsJsonAsync<CardDetails>("pidev/payment/addcart/"+clientid, c).ContinueWith((postTask) => postTask.Result.EnsureSuccessStatusCode());
            return RedirectToAction("Felicitation");
        }

        [System.Web.Http.HttpPost]
        public ActionResult charge(Charge c)
        {
            c.currency = "usd";
            c.description = "c bon ";
            var clientid = Session["clientid"];
            var basketid = Session["basketid"];
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:8085");           
            client.PostAsJsonAsync<Charge>("pidev/payment/charger/" + clientid +"/"+basketid , c).ContinueWith((postTask) => postTask.Result.EnsureSuccessStatusCode());
            return RedirectToAction("ClientVue","Client");
        }

        public ActionResult showPaymentForAdmin()
        {



            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:8085");
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage response = client.GetAsync("pidev/payment/getallpayment").Result;

            if (response.IsSuccessStatusCode)
            {
                var command = response.Content.ReadAsAsync<IEnumerable<Payment>>().Result;

                return View(command);

            }
            else
            {
                return View();
            }
        }


        [System.Web.Http.HttpGet]
        public ActionResult Felicitation()
        {
            TempData["SuccessMessage"] = "Deleted Successfully";
            return View("Felicitation");
        }

    }
}

ConsumeWebServices/Views/Personne/Create.cshtml
@model ConsumeWebServices.Models.Personne

@{
    ViewBag.Title = "Create";
}

<h2>Createdddd</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Personne</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.nom, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.nom, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nom, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.prenom, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.prenom, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.prenom, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.cin, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.cin, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.cin, "", new { @class = "text-danger" })
        </div>
    </div>qsdf

    <form action="@Url.Action("Create", "Payment")">
        <button type="submit" class="submit" />sign in
    </form>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>