finalPidev/Models/Topic.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace finalPidev.Models
{
    public class Topic
    {

        public int idTopic { get; set; }
        public String title { get; set; }
        public String content { get; set; }
        public DateTime creationDate { get; set; }
        public int numberViews { get; set; }
        public User userId { get; set; }
        public int? idUser { get; set; }
        
    }
}

finalPidev/Controllers/RatingTopicController.cs
using finalPidev.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace finalPidev.Controllers
{
    public class RatingTopicController : Controller
    {
        // GET: RatingTopic
        public ActionResult Index(int id)
        {
            IEnumerable<RatingTopic> ratingtopicList;
            HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("ratingtopic/DisplayEtoileByTopic/"+id.ToString()).Result;
            ratingtopicList = response.Content.ReadAsAsync<IEnumerable<RatingTopic>>().Result;
            return View(ratingtopicList);
        }
    }
}

finalPidev/Controllers/TopicController.cs
using finalPidev.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace finalPidev.Controllers
{
    public class TopicController : Controller
    {
        // GET: Topic
        public ActionResult Index()
        {
            IEnumerable<Topic> topicList;
            HttpResponseMessage response = GlobalVariables.WebApiClient.DeleteAsync("topic/DisplayTopics").Result;
            topicList = response.Content.ReadAsAsync<IEnumerable<Topic>>().Result;
            return View(topicList);
        }

        public ActionResult Create(int id = 0)
        {
            if (id == 0)
                return View(new Topic());
            else
            {
                HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("topic/getTopic/" + id.ToString()).Result;
                return View(response.Content.ReadAsAsync<Topic>().Result);
            }
        }
        [HttpPost]
        public ActionResult Create(Topic topic)
        {
            var userid = Session["userid"];
            if (topic.idTopic == 0)
            {
                HttpResponseMessage response = GlobalVariables.WebApiClient.PostAsJsonAsync("topic/addTopic/" + userid.ToString(), topic).Result;
                TempData["SuccessMessage"] = "Saved Successfully";
            }
            else
            {
                HttpResponseMessage response = GlobalVariables.WebApiClient.PutAsJsonAsync("topic/UpdateTopic/" + topic.idTopic + "/" + userid.ToString(), topic).Result;
                TempData["SuccessMessage"] = "Updated Successfully";
            }
            return RedirectToAction("Index");
        }


        public ActionResult Delete(int id)
        {
            var userid = Session["userid"];
            HttpResponseMessage response = GlobalVariables.WebApiClient.DeleteAsync("topic/deleteTopic/" + id.ToString() + "/" + userid.ToString()).Result;
            TempData["SuccessMessage"] = "Deleted Successfully";
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            int idtopic = id;
            Session["idtopic"] = idtopic;
            if (id == 0)
                return RedirectToAction("Index");
            else
            {

                HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("topic/getdetailsTopic/" + id.ToString()).Result;
                return View(response.Content.ReadAsAsync<Topic>().Result);

            }
        }
        
    }
}

finalPidev/Views/Topic/Create.cshtml
@model finalPidev.Models.Topic
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create</h2>

<div class="form-body">
    @using (Html.BeginForm())
    {
        @Html.HiddenFor(model => model.idTopic)
        @Html.HiddenFor(model => model.idUser)
        <div class="form-group">
            @Html.LabelFor(model => model.title)
            @Html.EditorFor(model => model.title)
            @Html.ValidationMessageFor(model => model.title)
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.content)
            @Html.EditorFor(model => model.content)
            @Html.ValidationMessageFor(model => model.content)
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.creationDate)
            @Html.EditorFor(model => model.creationDate)
            @Html.ValidationMessageFor(model => model.creationDate)
        </div>
        

        <div class="form-group">
            <input type="submit" value="Submit" class="btn button" />
            <input type="reset" value="Reset" class="btn button" />
        </div>
    }
</div>


@section scripts{
    @Scripts.Render("~/bundles/jqueryval");
}

finalPidev/Views/Topic/Details.cshtml
@model finalPidev.Models.Topic

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Topics</h4>
    <hr />
    <table class="table">
        <thead class="table-heading">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.content)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.creationDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.numberViews)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.userId.login)
                </th>
            </tr>
        </thead>
        <tr>

            <td>
                @Html.DisplayFor(model => model.title)
            </td>

            <td>
                @Html.DisplayFor(model => model.content)
            </td>

            <td>
                @Html.DisplayFor(model => model.creationDate)
            </td>

            <td>
                @Html.DisplayFor(model => model.numberViews)
            </td>

            <td>
                @Html.DisplayFor(model => model.userId.login)
            </td>
        </tr>
    </table>
</div>
<p>
    <a href="@Url.Action("Index", "RatingTopic", new { id = Model.idTopic })" class="btn btn-warning"> Rating</a>
    <a href="@Url.Action("Comment", "Topic", new { id = Model.idTopic })" class="btn btn-success"> Comments</a>
    
    <a href="@Url.Action("Index", "Topic")" class="btn btn-primary"> Back to List</a>
    
</p>

finalPidev/Views/Topic/Index.cshtml
@model IEnumerable<finalPidev.Models.Topic>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Get All Topics</h2>

<p>
    <a href="@Url.Action("Create","Topic")" class="btn btn-primary"><i class="fa fa-plus"></i> Create New</a>

</p>
<table class="table">
    <thead class="table-heading">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.content)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.creationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.numberViews)
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.content)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.creationDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.numberViews)
            </td>

            <td>
                <a href="@Url.Action("Create", "Topic", new { id = item.idTopic })" class="btn btn-warning"><i class="fa fa-pencil fa-fw"></i>  Edit</a>
                <a href="@Url.Action("Details", "Topic", new { id = item.idTopic })" class="btn btn-success"><i class="fa fa-eye"></i>  Détails</a>
                @{ int id = @item.idTopic;}
                <a href="@Url.Action("Delete", "Topic",new {id=@item.idTopic})" class="btn btn-danger"><i class="fa fa-trash-o"></i>Delete</a>
                
            </td>
        </tr>
    }

</table>